name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Setup and build
        run: |
          yarn ci
          yarn html classical-aesthetics
          yarn readme
          yarn 404 classical-aesthetics
          git add -f docs
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:build -f